### ISSUE TITLE
Buttons reappear when changing to a channel with the same name

### ISSUE THREAD

**Issue by Multarix** [Multarix/Discord-Remove-useless-chat-buttons#3]
As above, posting this here as an issue for a potential fix at some point.
preferably without making a mess of code checking each channel.

**Comment by Multarix** [comment]
For example, we could have it check the channel ID, but finding that in the mess that is discord's DOM is not fun

**Comment by Znunu** [comment]
What if we insert custom CSS into the header? I believe it's only cleared on a reload. We can use JS to auto generate the CSS and then insert it. This should also fix the other issue, with having to change channel first

**Comment by Multarix** [comment]
We can try, but I'm not really good with CSS so I have no idea what we should be adding

**Comment by Multarix** [comment]
![image](https://user-images.githubusercontent.com/29752805/124373194-86a36f00-dcd3-11eb-91e8-c5275dc3be8c.png)
We could do an extra check on this, to see if the server changed (as thats the most likely cause of when the bug will appear, though it doesn't fix the problem of it not triggering as soon as the script starts)

**Comment by Multarix** [comment]
Okay, with a bit of ugly change, this will work in all scenarios, the only issue is that any time the document changes at all, the observer triggers, though doesn't do anything So that includes messages, status updates, people typing and stopping typing, icon changes, everything. While the mutation Observer doesn't actually do anything due to the URL not changing, I'm not happy with it, there has to be a more elegant solution.

(The URL changes whenever we swap channels regardless of if the channel has the same name, this also works within the app)

```js
let prevURL = '';
new MutationObserver(() => {
  if(location.href === prevURL) return
  prevURL = location.href; // Set the previous URL to be the same as the current URL
  hideAnnoyingButtons(); // Run the script
}).observe(document, {subtree: true, childList: true}); // Whenever the "URL" changes, run the script

function hideAnnoyingButtons(){
	const buttonsToHide = ["Open GIF picker", "Open sticker picker", "Send a gift"] // Array of labels for buttons we want to remove
	for(button of buttonsToHide){ // Loop through the array
		const foundButton = document.querySelector(`[aria-label="${button}"]`); // Find the button
		if(foundButton) foundButton.remove() // If the button was found, remove it
	}
}
```

**Comment by Znunu** [comment]
Uhh, well a CSS style solution would look something like this
```JS
const buttonsToHide = ["Open GIF picker", "Open sticker picker", "Send a gift"]; var css = "";
buttonsToHide.forEach(button => css = css.concat(`[aria-label="${button}"]{display:none}`));
const style = document.createElement('style'); style.innerHTML = css;
document.head.appendChild(style);
```

**Comment by Multarix** [comment]
That'll indeed work, I generally tend to work with just JS so my CSS is limited, and a quick test confirms it to work. I'll make the change now.

**Comment by Znunu** [comment]
Can I add you on discord?

**Comment by Multarix** [comment]
Sure feel free, I'm Multarix#1337
